# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [5]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [13]:
A = np.arange(1, 16).reshape(3,5)

In [14]:
A


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
A.shape # shape of the array

(3, 5)

In [ ]:
A.size # antal element

15

In [ ]:
A.dtype # data type of array elements

dtype('int64')

In [ ]:
A.ndim # antal dimensioner


2

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [51]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [53]:
A = B - C
A


array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [54]:
A = B + C
A



array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [55]:
A = B @ C
A

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
D = np.arange(1, 10).reshape(3, 3) # 3x3 matrix with values from 1 to 9
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
E = np.exp(D) # e upphöjt till varje element i D
print(E)
E

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
E = D.min() #  minimum value in D
print(E)
E

1


np.int64(1)

In [ ]:
E = D.min(axis=0) # minimum value in each column
print(E)
E

[1 2 3]


array([1, 2, 3])

In [ ]:
E = D.min(axis=1) # minimum value in each row
print(E)
E

[1 4 7]


array([1, 4, 7])

In [59]:
# F = D.flat[np.argmin(D, axis=1)]
F = np.argmin(D) # position i 1D-array
print(F)
F

0


np.int64(0)

In [60]:
# F = D.flat[np.argmin(D, axis=1)]
F = np.argmin(D, axis=1)
print(F)
F

[0 0 0]


array([0, 0, 0])

In [61]:
S = D.sum() # sum of all elements
print(D) # print the original array D for reference
print(S)
S

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


np.int64(45)

In [62]:
M1 = D.mean(axis=0) # column-wise medelvärde
print(M1)
M1

[4. 5. 6.]


array([4., 5., 6.])

In [63]:
M = np.median(D, axis=0) # column-wise median
print(M)
M

[4. 5. 6.]


array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [241]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [242]:
A[1,2]

np.int64(8)

**Answer:**

In [70]:
# Färre specifierade index ger större mängd data. A ger hela matrisen, A[1] ger andra raden och A[1,2] 
# ger elementet i andra raden och tredje kolumnen.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [243]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [244]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [245]:
for i in A.flat: # Loopar igenom alla element i matrisen A som en 1D-array
    print(i)

print('-------X-------')

B = A.flatten() # Snyggare och enklare än ovan
print(B)
print(B[2] + B[8]) # <test> Summera 2:a och 8:e elementet i 1D-arrayen (indexering från 0)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
-------X-------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
12


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [74]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [75]:
# Vi konverterar en 1D-array till en 3D-array med 2 block, 3 rader och automatiskt beräknat antal kolumner (-1). 
# 1D-arrayen måste ha rätt antal element för att detta ska fungera (annars blir det fel).

# (Man kan också använda .reshape(2, 3, 5) direkt utan -1 i detta fall. Det fungerar också med 
# b = np.reshape(a, (2, 3, -1)) )

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [238]:
m1 = np.array([[1, 2], 
               [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [77]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [239]:
a = np.arange(1, 5).reshape(2,2)
print("a = \n", a)

b = np.array([2, 2])
print("b = \n", b)

a = 
 [[1 2]
 [3 4]]
b = 
 [2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [9]:
import numpy as np

def add_mult_matrices(m1, m2, oper: str):
    """
    Add or multiply two numpy arrays.
    oper: 'plus' or '+'        -> elementwise addition (requires same shape)
          'ganger' or '*'   -> matrix multiplication (requires m1.shape[1] == m2.shape[0])
    """
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 & m2 måste vara av typen numpy.ndarray")

    if oper in ('plus', '+'):
        if m1.shape != m2.shape:
            raise ValueError("För addition, matrisen måste ha samma form")
        return m1 + m2
    elif oper in ('ganger', '*'):
        if m1.ndim != 2 or m2.ndim != 2:
            raise ValueError("Matrix multiplikation måste vara 2D-arrayer")
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("För Matrismultiplikation, antal kolumner i första matrisen måste vara lika många som rader i andra matrisen")
        return m1 @ m2
    else:
        raise ValueError("Felaktig operator! oper måste vara 'plus'/'+' eller 'ganger'/'*'")

# --- Main start ---
# initialize A and B as numpy arrays (correct ndarray construction)
A = np.array([[1, 2, 3], # ok
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[10, 20, 30], # ok
              [40, 50, 60], 
              [70, 80, 90]])
"""
B = np.array([[10, 20, 30, 1], # ValueError: För addition, matrisen måste ha samma form (tester)
              [40, 50, 60, 2], 
              [70, 80, 90, 3]])
"""


# Print A and B with their shapes for checking
print(A, A.shape)
print(B, B.shape)
print()

print("Sum (elementwise addition):\n", add_mult_matrices(A, B, '+'), "\n")
print("Matrix multiplication (A @ B):\n", add_mult_matrices(A, B, '*'), "\n")

print("type(A):", type(A), "type(B):", type(B) )

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[10 20 30]
 [40 50 60]
 [70 80 90]] (3, 3)

Sum (elementwise addition):
 [[11 22 33]
 [44 55 66]
 [77 88 99]] 

Matrix multiplication (A @ B):
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]] 

type(A): <class 'numpy.ndarray'> type(B): <class 'numpy.ndarray'>


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [90]:
# Upg 10.1.1
import numpy as np

x = np.array([[4, 3]])
             
print ("(a)",x.shape)

(a) (1, 2)


x har dimensionen 1 x 2, en dimension

In [33]:
y = 5*x
print("(b) ",y)

(b)  [[20 15]]


In [34]:
y = 3*x
print("(c) ",y)


(c)  [[12  9]]


In [35]:
y = 5*x + 3*x
print("(d) ",y)

(d)  [[32 24]]


In [36]:
y = 8*x
print("(e) ",y) 

(e)  [[32 24]]


In [37]:
y = 4*x - x
print("(f) ",y)

(f)  [[12  9]]


In [41]:
y = x.T
print(y)
print ("(g) ",y.shape)

[[4]
 [3]]
(g)  (2, 1)


In [233]:

#z = x + x.T
z = x + np.transpose(x)
print("(h)\n",z)

(h)
 [[8 7]
 [7 6]]


(h) Nej, de har olika format 

In [96]:
# Norm med linalg   
n = np.linalg.norm(x)

print("(i) \n",n)
print(x)

(i) 
 5.0
[[4 3]]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
# Upg 10.1.2 *** Extra uppgift ***
v = np.array([[3], 
              [7], 
              [0], 
              [11]])
s = np.shape(v)
print("(a) Dimension\n",s)

v1 = v * 2
print("\n(b) Resultat\n",v1)

v2 = v * 5 + v * 2
print("\n(c) Resultat\n",v2)

v3 = v * 4 - v * 2
print("\n(d) Resultat\n",v3)

v4 = v.T
print("\n(e) Transponerad vektor\n",v4)
print("Dimension transponerad vektor:",v4.shape)

v5 = np.linalg.norm(v) # Norm med linalg

print("(f) Norm av v:\n",v5)

(a) Dimension
 (4, 1)

(b) Resultat
 [[ 6]
 [14]
 [ 0]
 [22]]

(c) Resultat
 [[21]
 [49]
 [ 0]
 [77]]

(d) Resultat
 [[ 6]
 [14]
 [ 0]
 [22]]

(e) Transponerad vektor
 [[ 3  7  0 11]]
Dimension transponerad vektor: (1, 4)
(f) Norm av v:
 13.379088160259652


In [107]:
# Upg 10.1.3

v1 = np.array([[4, 3, 1, 5]])
v2 = np.array([[2, 3, 1, 1]])

print(v1)
print(v2)

v6 = np.linalg.norm(v1)
print("\n(a) Norm av v1:\n",v6)

v7 = np.linalg.norm(v1 - v2)
print("\n(b) Avstånd mellan v1 och v2:\n",v7)


[[4 3 1 5]]
[[2 3 1 1]]

(a) Norm av v1:
 7.14142842854285

(b) Avstånd mellan v1 och v2:
 4.47213595499958


In [144]:
# Upg 10.2.1
import numpy as np # import numpy library

print("*** Notera att denna resultatyta är scrollbar ***\n")

A = np.array([[2, 1, -1], 
              [1, -1, 1]])
B = np.array([[4, -2, 1], 
              [2, -4, -2]])
C = np.array([[1, 2], 
              [2, 1]])
D = np.array([[3, 4], 
              [4, 3]])
E = np.array([[1], 
              [2]])
I = np.array([[1, 0], 
              [0, 1]])


w1 = 2*A
print("(a) Result (2A):\n",w1)

w2 = B - 2*A
print("\n(b) Result (B - 2A):\n",w2)

w3 = 3*C - 2*E
print("\n(c) Result (3C - 2E):\n",w3)

w4 = 2*D - 3*C
print("\n(d) Result (2D - 3C):\n",w4)

w5 = np.transpose(D) + 2*D
print("\n(e) Result (D.T + 2D):\n",w5)

w6 = 2 * np.transpose(C) - 2 * np.transpose(D)
print("\n(f) Result (2C.T - 2D.T):\n",w6)


try:
    w7 = np.transpose(A) - B
    print("\n(g) Result (A.T - B):\n",w7)
except ValueError as e:
    print("\n(g) Error (A.T - B):\n",e)

try:
    w8 = A @ C
    print("\n(h) Result (A @ C):\n",w8)
except ValueError as e:
    print("\n(h) Error (A @ C):\n",e)

w9 = C * D
print("\n(i) Result (C * D):\n",w9)

try:
    w10 = C @ B
    print("\n(j) Result (C @ B):\n",w10)
except ValueError as e:
    print("\n(j) Error (C @ B):\n",e)

w11 = C @ I
print("\n(k) Result (C @ I):\n",w11)

w12 = A @ np.transpose(B)
print("\n(l) Result (A @ B.T):\n",w12)

*** Notera att denna resultatyta är scrollbar ***

(a) Result (2A):
 [[ 4  2 -2]
 [ 2 -2  2]]

(b) Result (B - 2A):
 [[ 0 -4  3]
 [ 0 -2 -4]]

(c) Result (3C - 2E):
 [[ 1  4]
 [ 2 -1]]

(d) Result (2D - 3C):
 [[3 2]
 [2 3]]

(e) Result (D.T + 2D):
 [[ 9 12]
 [12  9]]

(f) Result (2C.T - 2D.T):
 [[-4 -4]
 [-4 -4]]

(g) Error (A.T - B):
 operands could not be broadcast together with shapes (3,2) (2,3) 

(h) Error (A @ C):
 matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

(i) Result (C * D):
 [[3 8]
 [8 3]]

(j) Result (C @ B):
 [[  8 -10  -3]
 [ 10  -8   0]]

(k) Result (C @ I):
 [[1 2]
 [2 1]]

(l) Result (A @ B.T):
 [[5 2]
 [7 4]]


In [ ]:
# Upg 10.2.2 

import numpy as np # import numpy library

A = np.array([[2, 3, 4], 
              [5, 4, 1]])
# print("A:\n",A)
B = np.transpose(A)
# print("A.T:\n",B)
S = A @ B 
print("Result S:\n",S)



Result S:
 [[29 26]
 [26 42]]


In [ ]:
# Upg 10.2.3


A = np.array([[1, 2], 
              [2, 4]])
B = np.array([[2, 1],
              [1, 3]])
C = np.array([[4, 3],
              [0, 2]])

#r1 = (A @ B) 
#r2 = (A @ C)
#print("Result AB:\n",r1)
#print("Result AC:\n",r2)

s1 = np.array_equal(A@B, A@C)
print("\nAre AB and AC equal? ", s1)

s2 = np.array_equal(B, C)
print("Are B and C equal? ", s2)



Are AB and AC equal?  True
Are B and C equal?  False


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [231]:
v1 = np.arange(4)
v2 = v1[-2:]
v2[1] = 123
print("\n",v1, v1.base is None )
print("\n",v2,v2.base is None )



 [  0   1   2 123] True

 [  2 123] False


Enl Numpy-länken ovan så skapar grundläggande (basic) indexering alltid 'views'. Views är en vy över originalet, om man förändrar värden i en vy så ändras även originalet. Samma minnesceller.
För att använda en delmängd av data UTAN att påverka källan så bör man använda funktionen copy (se exempel nedan).
M h a base (is None, booleansk svar) kontrolleras om det är en view eller kopia. None - kopia (True), annars original strängen (se nedan).

In [ ]:
v1 = np.arange(4)
v2 = v1.copy() # create a copy of v1 to avoid modifying it
v2 = v2[-2:]
v2[1] = 123
print("v1 \n",v1, v1.base is None)
print("v2 \n",v2, v2.base is None) # check that v2 is independent of v1

v1 
 [0 1 2 3] True
v2 
 [  2 123] False


Tack för i år! Detta var kunskapskontroll 2.1 med lite extra.